version: "3.7"
services:
  app:
    build: .
    environment:
      CRAWLERSTACK_ANTICAPTCHA_DATABASE_URL: mysql+aiomysql://root:123@mysql:3306/test
    ports:
      - "5000:8000"
    networks:
      - app

networks:
  app:
    external: true