version: "3.7"
services:
  app:
    build: .
    environment:
      CRAWLERSTACK_ANTICAPTCHA_DATABASE_URL:
    ports:
      - "5000:8000"
    networks:
      - app

networks:
  app:
    external: true