"""init_table

Revision ID: e306a0df04db
Revises: 1f9068250d7b
Create Date: 2022-10-17 18:05:56.061683

"""
from pathlib import Path

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
from crawlerstack_anticaptcha.config import settings

revision = 'e306a0df04db'
down_revision = '1f9068250d7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    category_table = op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('captcha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=True, comment='Id generated from filename'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='Captcha type id'),
    sa.Column('file_type', sa.String(length=255), nullable=True, comment='Image file type'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='Creation time'),
    sa.Column('success', sa.Boolean(), nullable=True, comment='Explain success'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.bulk_insert(
        category_table,
        [
            {
                "name": "SliderCaptcha",
                "path": str(Path(settings.IMAGE_SAVE_PATH).joinpath(Path('slider-captcha')))
            },
            {
                "name": "RotatedCaptcha",
                "path": str(Path(settings.IMAGE_SAVE_PATH).joinpath(Path('rotated-captcha')))
            },
            {
                "name": "NumericalCaptcha",
                "path": str(Path(settings.IMAGE_SAVE_PATH).joinpath(Path('numerical_captcha')))
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('captcha')
    op.drop_table('category')
    # ### end Alembic commands ###
