# The directory where the uploaded files are saved
image_save_path: /tmp/captcha-service


# log config
log_path: /tmp/captcha-service
log_level: INFO

# sql database config.
database_url: sqlite+aiosqlite:////tmp/captcha_database.db

show_sql: false
