# The directory where the uploaded files are saved
image_save_path: /tmp/captcha


# log config
log_path: /tmp/log
log_level: INFO

# sql database config.
database_url: sqlite+aiosqlite:////tmp/captcha_database.db
