# The directory where the uploaded files are saved
captcha_image_path: /tmp/crawlerstack/anticaptcha/images

# log config
log_path: /tmp/crawlerstack/anticaptcha/log
log_level: INFO

# sql database config.
database_url: sqlite+aiosqlite:////tmp/crawlerstack/anticaptcha/db.sqlite

show_sql: false

tesseract_cmd_path: