name: main

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
          pip install poetry
      - name: Test with tox
        run: |
          tox -e py

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2

      - run: |
          pip install tox
          pip install isort
          pip install pylint
      - run: |
          tox -e isort
          tox -e pylint

  junit-coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
          pip install poetry
      - name: Test with tox
        run: |
          tox -e py

      - name: Test Reports
        uses: xportation/junit-coverage-report@main
        with:
          junit-path: ./pytest.xml 
          coverage-path: ./coverage.xml
